apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-webapp
  labels:
    app: springboot-webapp
spec:
  selector:
    matchLabels:
        app: springboot-webapp
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: springboot-webapp
    spec:
      containers:
        - name: springboot-webapp
          image: pabonwalt/springboot-webapp:latest
          ports:
            - containerPort: 8081
              protocol: TCP
          imagePullPolicy: Always
